version: '3'
 
services:
  web: &web
    build: .
    command: bash -c "cd famPay && python manage.py migrate --run-syncdb && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - .:/code

  
  celery_worker:
    <<: *web
    restart: always
    depends_on:
      - web
      - redis
    command: bash -c "cd famPay && celery -A famPay worker -l info"
    ports: []
    volumes:
      - .:/code

  
  celery-beat:
    <<: *web
    command: bash -c "cd famPay && celery -A famPay beat -l info"
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    ports: []

    
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - .:/code




    