version: '3'
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 127.0.0.1:8000"
    
    redis:
      image: redis:alpine
    celery:
      restart: always
      build:
        context: .
      command: >
        sh -c "celery -A famPay worker -l info &&
               celery -A famPay beat "
      volumes:
        - ./app:/app
      depends_on:
        - redis
        - app